### ISSUE TITLE
Comodo valkyrie verdict flagging fnm Chocolatey package

### ISSUE THREAD

**Issue by hellosmithy** [CMeeg/fnm-chocolatey#1]
The virus scan results linked to at https://community.chocolatey.org/packages/fnm#virus are flagging the fnm.exe file.

"1 sandbox flagged this file as malicious"

It appears to be a Comodo valkyrie verdict which are binary:

"Valkyrie Threat Intelligence
Valkyrie Verdict is the only file verdicting solution that classifies ALL files in a network as either 100% safe (confidently pushing it to our global whitelist, 2.6 billion files and growing) or 100% malicious (confidently pushing it to our global blacklist which is at 700 million+)."

Any idea why that IP address (209.197.3.8) is being called?

<img width="1362" alt="Screenshot 2021-12-21 at 14 35 41" src="https://user-images.githubusercontent.com/866604/146947324-1a46431b-4feb-4e54-bf21-9aba5efb81dd.png">

**Comment by CMeeg** [comment]
Tbh, I don't know. I'm taking the Windows binaries from the [fnm](https://github.com/Schniz/fnm) release and packaging for distrubution via Chocolatey. I don't know the internals of the tool at all. The best place to raise this issue would be on the fnm repo. Sorry I can't help.

I can see that this was being flagged up until the last [1.28.2 release](https://community.chocolatey.org/packages/fnm/1.28.2#virus), but the latest [1.29.1 release](https://community.chocolatey.org/packages/fnm#virus) no longer reports the issue.
